import org.bukkit.Material;

//This function gets a material from a block ID
//  Some values aren't needed. Mostly need this for shops to continue working somewhat correctly.
public class BlockIDUtil {
	public static Material getMaterialFromID(int blockID, int dmgValue) {
		Material returnMaterial = null;
		switch (blockID) {
			case 0: returnMaterial = Material.AIR;
			break;
			case 1: returnMaterial = Material.STONE;
			break;
			case 2: returnMaterial = Material.GRASS;
			break;
			case 3: returnMaterial = Material.DIRT;
			break;
			case 4: returnMaterial = Material.COBBLESTONE;
			break;
			case 5: returnMaterial = Material.OAK_WOOD;
			break;
			case 6: returnMaterial = Material.OAK_SAPLING;
			break;
			case 7: returnMaterial = Material.BEDROCK;
			break;
			case 8: returnMaterial = Material.WATER;
			break;
			case 9: returnMaterial = Material.WATER;
			break;
			case 10: returnMaterial = Material.LAVA;
			break;
			case 11: returnMaterial = Material.LAVA;
			break;
			case 12: returnMaterial = Material.SAND;
			break;
			case 13: returnMaterial = Material.GRAVEL;
			break;
			case 14: returnMaterial = Material.GOLD_ORE;
			break;
			case 15: returnMaterial = Material.IRON_ORE;
			break;
			case 16: returnMaterial = Material.COAL_ORE;
			break;
			case 17: returnMaterial = Material.OAK_LOG;
			break;
			case 18: returnMaterial = Material.OAK_LEAVES;
			break;
			case 19: returnMaterial = Material.SPONGE;
			break;
			case 20: returnMaterial = Material.GLASS;
			break;
			case 21: returnMaterial = Material.LAPIS_ORE;
			break;
			case 22: returnMaterial = Material.LAPIS_BLOCK;
			break;
			case 23: returnMaterial = Material.DISPENSER;
			break;
			case 24: returnMaterial = Material.SANDSTONE;
			break;
			case 25: returnMaterial = Material.NOTE_BLOCK;
			break;
			case 26: returnMaterial = Material.RED_BED;
			break;
			case 27: returnMaterial = Material.POWERED_RAIL;
			break;
			case 28: returnMaterial = Material.DETECTOR_RAIL;
			break;
			case 29: returnMaterial = Material.STICKY_PISTON; //Sticky piston base
			break;
			case 30: returnMaterial = Material.COBWEB;
			break;
			case 31: returnMaterial = Material.TALL_GRASS;
			break;
			case 32: returnMaterial = Material.DEAD_BUSH;
			break;
			case 33: returnMaterial = Material.PISTON; //Piston base
			break;
			case 34: returnMaterial = Material.PISTON; //Piston extension
			break;
			case 35: returnMaterial = Material.WHITE_WOOL;
			break;
			case 36: returnMaterial = Material.PISTON;
			break;
			case 37: returnMaterial = Material.DANDELION; //Is this correct?
			break;
			case 38: returnMaterial = Material.ROSE_BUSH; //Is this correct?
			break;
			case 39: returnMaterial = Material.BROWN_MUSHROOM;
			break;
			case 40: returnMaterial = Material.RED_MUSHROOM;
			break;
			case 41: returnMaterial = Material.GOLD_BLOCK;
			break;
			case 42: returnMaterial = Material.IRON_BLOCK;
			break;
			case 43: returnMaterial = Material.STONE_SLAB; //Double stone slab, replace with stone slab.
			break;
			case 44: returnMaterial = Material.STONE_SLAB;
			break;
			case 45: returnMaterial = Material.BRICK;
			break;
			case 46: returnMaterial = Material.TNT;
			break;
			case 47: returnMaterial = Material.BOOKSHELF;
			break;
			case 48: returnMaterial = Material.MOSSY_COBBLESTONE;
			break;
			case 49: returnMaterial = Material.OBSIDIAN;
			break;
			case 50: returnMaterial = Material.TORCH;
			break;
			case 51: returnMaterial = Material.FIRE;
			break;
			case 52: returnMaterial = Material.STONE; //Mob spawner, replace with stone
			break;
			case 53: returnMaterial = Material.OAK_STAIRS;
			break;
			case 54: returnMaterial = Material.CHEST;
			break;
			case 55: returnMaterial = Material.REDSTONE_WIRE;
			break;
			case 56: returnMaterial = Material.DIAMOND_ORE;
			break;
			case 57: returnMaterial = Material.DIAMOND_BLOCK;
			break;
			case 58: returnMaterial = Material.CRAFTING_TABLE;
			break;
			case 59: returnMaterial = Material.WHEAT; //Crops, replace with wheat
			break;
			case 60: returnMaterial = Material.DIRT; //Soil, replace with dirt
			break;
			case 61: returnMaterial = Material.FURNACE;
			break;
			case 62: returnMaterial = Material.FURNACE; //Burning furnace, replace with furnace
			break;
			case 63: returnMaterial = Material.SIGN; //Sign post, replace with sign
			break;
			case 64: returnMaterial = Material.OAK_DOOR;
			break;
			case 65: returnMaterial = Material.LADDER;
			break;
			case 66: returnMaterial = Material.RAIL;
			break;
			case 67: returnMaterial = Material.COBBLESTONE_STAIRS;
			break;
			case 68: returnMaterial = Material.WALL_SIGN;
			break;
			case 69: returnMaterial = Material.LEVER;
			break;
			case 70: returnMaterial = Material.STONE_PRESSURE_PLATE;
			break;
			case 71: returnMaterial = Material.IRON_DOOR; //Iron door block, replace with iron door
			break;
			case 72: returnMaterial = Material.OAK_PRESSURE_PLATE;
			break;
			case 73: returnMaterial = Material.REDSTONE_ORE;
			break;
			case 74: returnMaterial = Material.REDSTONE_ORE; //Glowing redstone ore, replace with restone ore
			break;
			case 75: returnMaterial = Material.REDSTONE_TORCH; //Redstone torch off, replace with redstone torch
			break;
			case 76: returnMaterial = Material.REDSTONE_TORCH; //Redstone torch on, replace with redstone torch
			break;
			case 77: returnMaterial = Material.STONE_BUTTON;
			break;
			case 78: returnMaterial = Material.SNOW;
			break;
			case 79: returnMaterial = Material.ICE;
			break;
			case 80: returnMaterial = Material.SNOW_BLOCK;
			break;
			case 81: returnMaterial = Material.CACTUS;
			break;
			case 82: returnMaterial = Material.CLAY;
			break;
			case 83: returnMaterial = Material.SUGAR_CANE; //Sugar cane block, replace with sugar cane
			break;
			case 84: returnMaterial = Material.JUKEBOX;
			break;
			case 85: returnMaterial = Material.OAK_FENCE;
			break;
			case 86: returnMaterial = Material.PUMPKIN;
			break;
			case 87: returnMaterial = Material.NETHERRACK;
			break;
			case 88: returnMaterial = Material.SOUL_SAND;
			break;
			case 89: returnMaterial = Material.GLOWSTONE;
			break;
			case 90: returnMaterial = Material.NETHER_PORTAL;
			break;
			case 91: returnMaterial = Material.JACK_O_LANTERN;
			break;
			case 92: returnMaterial = Material.CAKE; //Cake block, replace with cake
			break;
			case 93: returnMaterial = Material.REPEATER; //Repeater variation, not meant for use
			break;
			case 94: returnMaterial = Material.REPEATER; //Repeater variation, not meant for use
			break;
			case 95: returnMaterial = Material.WHITE_STAINED_GLASS;
			break;
			case 96: returnMaterial = Material.OAK_TRAPDOOR;
			break;
			case 97: returnMaterial = Material.STONE; //Monster eggs, not meant for use
			break;
			case 98: returnMaterial = Material.STONE_BRICKS;
			break;
			case 99: returnMaterial = Material.BROWN_MUSHROOM_BLOCK;
			break;
			case 100: returnMaterial = Material.RED_MUSHROOM_BLOCK;
			break;
			case 101: returnMaterial = Material.IRON_BARS;
			break;
			case 102: returnMaterial = Material.GLASS_PANE;
			break;
			case 103: returnMaterial = Material.MELON_SLICE; //Melon block, not meant for use
			break;
			case 104: returnMaterial = Material.PUMPKIN_STEM;
			break;
			case 105: returnMaterial = Material.MELON_STEM;
			break;
			case 106: returnMaterial = Material.VINE;
			break;
			case 107: returnMaterial = Material.OAK_FENCE_GATE;
			break;
			case 108: returnMaterial = Material.BRICK_STAIRS;
			break;
			case 109: returnMaterial = Material.STONE_BRICK_STAIRS;
			break;
			case 110: returnMaterial = Material.MYCELIUM;
			break;
			case 111: returnMaterial = Material.LILY_PAD;
			break;
			case 112: returnMaterial = Material.NETHER_BRICK;
			break;
			case 113: returnMaterial = Material.NETHER_BRICK_FENCE;
			break;
			case 114: returnMaterial = Material.NETHER_BRICK_STAIRS;
			break;
			case 115: returnMaterial = Material.NETHER_WART;
			break;
			case 116: returnMaterial = Material.ENCHANTING_TABLE;
			break;
			case 117: returnMaterial = Material.BREWING_STAND;
			break;
			case 118: returnMaterial = Material.CAULDRON;
			break;
			case 119: returnMaterial = Material.END_PORTAL;
			break;
			case 120: returnMaterial = Material.END_PORTAL_FRAME;
			break;
			case 121: returnMaterial = Material.END_STONE;
			break;
			case 122: returnMaterial = Material.DRAGON_EGG;
			break;
			case 123: returnMaterial = Material.REDSTONE_LAMP;
			break;
			case 124: returnMaterial = Material.REDSTONE_LAMP;
			break;
			case 125: returnMaterial = Material.OAK_SLAB; //Wood double step, not meant for use
			break;
			case 126: returnMaterial = Material.OAK_SLAB;
			break;
			case 127: returnMaterial = Material.COCOA;
			break;
			case 128: returnMaterial = Material.SANDSTONE_STAIRS;
			break;
			case 129: returnMaterial = Material.EMERALD_ORE;
			break;
			case 130: returnMaterial = Material.ENDER_CHEST;
			break;
			case 131: returnMaterial = Material.TRIPWIRE_HOOK;
			break;
			case 132: returnMaterial = Material.TRIPWIRE;
			break;
			case 133: returnMaterial = Material.EMERALD_BLOCK;
			break;
			case 134: returnMaterial = Material.SPRUCE_STAIRS;
			break;
			case 135: returnMaterial = Material.BIRCH_STAIRS;
			break;
			case 136: returnMaterial = Material.JUNGLE_STAIRS;
			break;
			case 137: returnMaterial = Material.STONE; //Command block, not meant for use
			break;
			case 138: returnMaterial = Material.BEACON;
			break;
			case 139: returnMaterial = Material.COBBLESTONE_WALL;
			break;
			case 140: returnMaterial = Material.FLOWER_POT;
			break;
			case 141: returnMaterial = Material.CARROT;
			break;
			case 142: returnMaterial = Material.POTATO;
			break;
			case 143: returnMaterial = Material.OAK_BUTTON;
			break;
			case 144: returnMaterial = Material.SKELETON_SKULL; //Default to skeleton skull
			break;
			case 145: returnMaterial = Material.ANVIL;
			break;
			case 146: returnMaterial = Material.TRAPPED_CHEST;
			break;
			case 147: returnMaterial = Material.LIGHT_WEIGHTED_PRESSURE_PLATE;
			break;
			case 148: returnMaterial = Material.HEAVY_WEIGHTED_PRESSURE_PLATE;
			break;
			case 149: returnMaterial = Material.COMPARATOR;
			break;
			case 150: returnMaterial = Material.COMPARATOR;
			break;
			case 151: returnMaterial = Material.DAYLIGHT_DETECTOR;
			break;
			case 152: returnMaterial = Material.REDSTONE_BLOCK;
			break;
			case 153: returnMaterial = Material.NETHER_QUARTZ_ORE;
			break;
			case 154: returnMaterial = Material.HOPPER;
			break;
			case 155: returnMaterial = Material.QUARTZ_BLOCK;
			break;
			case 156: returnMaterial = Material.QUARTZ_STAIRS;
			break;
			case 157: returnMaterial = Material.ACTIVATOR_RAIL;
			break;
			case 158: returnMaterial = Material.DROPPER;
			break;
			case 159: returnMaterial = Material.WHITE_TERRACOTTA; //Stained clay
			break;
			case 160: returnMaterial = Material.WHITE_STAINED_GLASS_PANE;
			break;
			case 161: returnMaterial = Material.ACACIA_LEAVES;
			break;
			case 162: returnMaterial = Material.ACACIA_LOG;
			break;
			case 163: returnMaterial = Material.ACACIA_STAIRS;
			break;
			case 164: returnMaterial = Material.DARK_OAK_STAIRS;
			break;
			case 165: returnMaterial = Material.SLIME_BLOCK;
			break;
			case 166: returnMaterial = Material.BARRIER;
			break;
			case 167: returnMaterial = Material.IRON_TRAPDOOR;
			break;
			case 168: returnMaterial = Material.PRISMARINE;
			break;
			case 169: returnMaterial = Material.SEA_LANTERN;
			break;
			case 170: returnMaterial = Material.HAY_BLOCK;
			break;
			case 171: returnMaterial = Material.WHITE_CARPET;
			break;
			case 172: returnMaterial = Material.TERRACOTTA;
			break;
			case 173: returnMaterial = Material.COAL_BLOCK;
			break;
			case 174: returnMaterial = Material.PACKED_ICE;
			break;
			case 175: returnMaterial = Material.STONE; //Double plant, not meant for use
			break;
			case 176: returnMaterial = Material.GRAY_BANNER;
			break;
			case 177: returnMaterial = Material.GRAY_BANNER;
			break;
			case 178: returnMaterial = Material.DAYLIGHT_DETECTOR;
			break;
			case 179: returnMaterial = Material.RED_SANDSTONE;
			break;
			case 180: returnMaterial = Material.RED_SANDSTONE_STAIRS;
			break;
			case 181: returnMaterial = Material.STONE; //Double red sandstone slab, not meant for use
			break;
			case 182: returnMaterial = Material.RED_SANDSTONE_SLAB;
			break;
			case 183: returnMaterial = Material.SPRUCE_FENCE_GATE;
			break;
			case 184: returnMaterial = Material.BIRCH_FENCE_GATE;
			break;
			case 185: returnMaterial = Material.JUNGLE_FENCE_GATE;
			break;
			case 186: returnMaterial = Material.DARK_OAK_FENCE_GATE;
			break;
			case 187: returnMaterial = Material.ACACIA_FENCE_GATE;
			break;
			case 188: returnMaterial = Material.SPRUCE_FENCE;
			break;
			case 189: returnMaterial = Material.BIRCH_FENCE;
			break;
			case 190: returnMaterial = Material.JUNGLE_FENCE;
			break;
			case 191: returnMaterial = Material.DARK_OAK_FENCE;
			break;
			case 192: returnMaterial = Material.ACACIA_FENCE;
			break;
			case 193: returnMaterial = Material.SPRUCE_DOOR;
			break;
			case 194: returnMaterial = Material.BIRCH_DOOR;
			break;
			case 195: returnMaterial = Material.JUNGLE_DOOR;
			break;
			case 196: returnMaterial = Material.ACACIA_DOOR;
			break;
			case 197: returnMaterial = Material.DARK_OAK_DOOR;
			break;
			case 198: returnMaterial = Material.END_ROD;
			break;
			case 199: returnMaterial = Material.CHORUS_PLANT;
			break;
			case 200: returnMaterial = Material.CHORUS_FLOWER;
			break;
			case 201: returnMaterial = Material.PURPUR_BLOCK;
			break;
			case 202: returnMaterial = Material.PURPUR_PILLAR;
			break;
			case 203: returnMaterial = Material.PURPUR_STAIRS;
			break;
			case 204: returnMaterial = Material.STONE; //Purpur double slab, not meant for use
			break;
			case 205: returnMaterial = Material.PURPUR_SLAB;
			break;
			case 206: returnMaterial = Material.END_STONE_BRICKS;
			break;
			case 207: returnMaterial = Material.STONE; //Beetroot block, not meant for use
			break;
			case 208: returnMaterial = Material.GRASS_PATH;
			break;
			case 209: returnMaterial = Material.END_GATEWAY;
			break;
			case 210: returnMaterial = Material.STONE; //Command block, not meant for use
			break;
			case 211: returnMaterial = Material.STONE; //Command block, not meant for use
			break;
			case 212: returnMaterial = Material.FROSTED_ICE;
			break;
			case 213: returnMaterial = Material.MAGMA_BLOCK;
			break;
			case 214: returnMaterial = Material.NETHER_WART_BLOCK;
			break;
			case 215: returnMaterial = Material.RED_NETHER_BRICKS;
			break;
			case 216: returnMaterial = Material.BONE_BLOCK;
			break;
			case 217: returnMaterial = Material.STRUCTURE_VOID;
			break;
			case 218: returnMaterial = Material.OBSERVER;
			break;
			case 219: returnMaterial = Material.WHITE_SHULKER_BOX;
			break;
			case 220: returnMaterial = Material.ORANGE_SHULKER_BOX;
			break;
			case 221: returnMaterial = Material.MAGENTA_SHULKER_BOX;
			break;
			case 222: returnMaterial = Material.LIGHT_BLUE_SHULKER_BOX;
			break;
			case 223: returnMaterial = Material.YELLOW_SHULKER_BOX;
			break;
			case 224: returnMaterial = Material.LIME_SHULKER_BOX;
			break;
			case 225: returnMaterial = Material.PINK_SHULKER_BOX;
			break;
			case 226: returnMaterial = Material.GRAY_SHULKER_BOX;
			break;
			case 227: returnMaterial = Material.LIGHT_GRAY_SHULKER_BOX;
			break;
			case 228: returnMaterial = Material.CYAN_SHULKER_BOX;
			break;
			case 229: returnMaterial = Material.PURPLE_SHULKER_BOX;
			break;
			case 230: returnMaterial = Material.BLUE_SHULKER_BOX;
			break;
			case 231: returnMaterial = Material.BROWN_SHULKER_BOX;
			break;
			case 232: returnMaterial = Material.GREEN_SHULKER_BOX;
			break;
			case 233: returnMaterial = Material.RED_SHULKER_BOX;
			break;
			case 234: returnMaterial = Material.BLACK_SHULKER_BOX;
			break;
			case 235: returnMaterial = Material.WHITE_GLAZED_TERRACOTTA;
			break;
			case 236: returnMaterial = Material.ORANGE_GLAZED_TERRACOTTA;
			break;
			case 237: returnMaterial = Material.MAGENTA_GLAZED_TERRACOTTA;
			break;
			case 238: returnMaterial = Material.LIGHT_BLUE_GLAZED_TERRACOTTA;
			break;
			case 239: returnMaterial = Material.YELLOW_GLAZED_TERRACOTTA;
			break;
			case 240: returnMaterial = Material.LIME_GLAZED_TERRACOTTA;
			break;
			case 241: returnMaterial = Material.PINK_GLAZED_TERRACOTTA;
			break;
			case 242: returnMaterial = Material.GRAY_GLAZED_TERRACOTTA;
			break;
			case 243: returnMaterial = Material.LIGHT_GRAY_GLAZED_TERRACOTTA;
			break;
			case 244: returnMaterial = Material.CYAN_GLAZED_TERRACOTTA;
			break;
			case 245: returnMaterial = Material.PURPLE_GLAZED_TERRACOTTA;
			break;
			case 246: returnMaterial = Material.BLUE_GLAZED_TERRACOTTA;
			break;
			case 247: returnMaterial = Material.BROWN_GLAZED_TERRACOTTA;
			break;
			case 248: returnMaterial = Material.GREEN_GLAZED_TERRACOTTA;
			break;
			case 249: returnMaterial = Material.RED_GLAZED_TERRACOTTA;
			break;
			case 250: returnMaterial = Material.BLACK_GLAZED_TERRACOTTA;
			break;
			case 251: returnMaterial = Material.GRAY_CONCRETE;
			break;
			case 252: returnMaterial = Material.GRAY_CONCRETE_POWDER;
			break;
			case 255: returnMaterial = Material.STRUCTURE_BLOCK;
			break;
			case 256: returnMaterial = Material.IRON_SHOVEL;
			break;
			case 257: returnMaterial = Material.IRON_PICKAXE;
			break;
			case 258: returnMaterial = Material.IRON_AXE;
			break;
			case 259: returnMaterial = Material.FLINT_AND_STEEL;
			break;
			case 260: returnMaterial = Material.APPLE;
			break;
			case 261: returnMaterial = Material.BOW;
			break;
			case 262: returnMaterial = Material.ARROW;
			break;
			case 263: returnMaterial = Material.COAL;
			break;
			case 264: returnMaterial = Material.DIAMOND;
			break;
			case 265: returnMaterial = Material.IRON_INGOT;
			break;
			case 266: returnMaterial = Material.GOLD_INGOT;
			break;
			case 267: returnMaterial = Material.IRON_SWORD;
			break;
			case 268: returnMaterial = Material.WOODEN_SWORD;
			break;
			case 269: returnMaterial = Material.WOODEN_SHOVEL;
			break;
			case 270: returnMaterial = Material.WOODEN_PICKAXE;
			break;
			case 271: returnMaterial = Material.WOODEN_AXE;
			break;
			case 272: returnMaterial = Material.STONE_SWORD;
			break;
			case 273: returnMaterial = Material.STONE_SHOVEL;
			break;
			case 274: returnMaterial = Material.STONE_PICKAXE;
			break;
			case 275: returnMaterial = Material.STONE_AXE;
			break;
			case 276: returnMaterial = Material.DIAMOND_SWORD;
			break;
			case 277: returnMaterial = Material.DIAMOND_SHOVEL;
			break;
			case 278: returnMaterial = Material.DIAMOND_PICKAXE;
			break;
			case 279: returnMaterial = Material.DIAMOND_AXE;
			break;
			case 280: returnMaterial = Material.STICK;
			break;
			case 281: returnMaterial = Material.BOWL;
			break;
			case 282: returnMaterial = Material.MUSHROOM_STEW;
			break;
			case 283: returnMaterial = Material.GOLDEN_SWORD;
			break;
			case 284: returnMaterial = Material.GOLDEN_SHOVEL;
			break;
			case 285: returnMaterial = Material.GOLDEN_PICKAXE;
			break;
			case 286: returnMaterial = Material.GOLDEN_AXE;
			break;
			case 287: returnMaterial = Material.STRING;
			break;
			case 288: returnMaterial = Material.FEATHER;
			break;
			case 289: returnMaterial = Material.GUNPOWDER;
			break;
			case 290: returnMaterial = Material.WOODEN_HOE;
			break;
			case 291: returnMaterial = Material.STONE_HOE;
			break;
			case 292: returnMaterial = Material.IRON_HOE;
			break;
			case 293: returnMaterial = Material.DIAMOND_HOE;
			break;
			case 294: returnMaterial = Material.GOLDEN_HOE;
			break;
			case 295: returnMaterial = Material.WHEAT_SEEDS;
			break;
			case 296: returnMaterial = Material.WHEAT;
			break;
			case 297: returnMaterial = Material.BREAD;
			break;
			case 298: returnMaterial = Material.LEATHER_HELMET;
			break;
			case 299: returnMaterial = Material.LEATHER_CHESTPLATE;
			break;
			case 300: returnMaterial = Material.LEATHER_LEGGINGS;
			break;
			case 301: returnMaterial = Material.LEATHER_BOOTS;
			break;
			case 302: returnMaterial = Material.CHAINMAIL_HELMET;
			break;
			case 303: returnMaterial = Material.CHAINMAIL_CHESTPLATE;
			break;
			case 304: returnMaterial = Material.CHAINMAIL_LEGGINGS;
			break;
			case 305: returnMaterial = Material.CHAINMAIL_BOOTS;
			break;
			case 306: returnMaterial = Material.IRON_HELMET;
			break;
			case 307: returnMaterial = Material.IRON_CHESTPLATE;
			break;
			case 308: returnMaterial = Material.IRON_LEGGINGS;
			break;
			case 309: returnMaterial = Material.IRON_BOOTS;
			break;
			case 310: returnMaterial = Material.DIAMOND_HELMET;
			break;
			case 311: returnMaterial = Material.DIAMOND_CHESTPLATE;
			break;
			case 312: returnMaterial = Material.DIAMOND_LEGGINGS;
			break;
			case 313: returnMaterial = Material.DIAMOND_BOOTS;
			break;
			case 314: returnMaterial = Material.GOLDEN_HELMET;
			break;
			case 315: returnMaterial = Material.GOLDEN_CHESTPLATE;
			break;
			case 316: returnMaterial = Material.GOLDEN_LEGGINGS;
			break;
			case 317: returnMaterial = Material.GOLDEN_BOOTS;
			break;
			case 318: returnMaterial = Material.FLINT;
			break;
			case 319: returnMaterial = Material.PORKCHOP;
			break;
			case 320: returnMaterial = Material.COOKED_PORKCHOP;
			break;
			case 321: returnMaterial = Material.PAINTING;
			break;
			case 322: returnMaterial = Material.GOLDEN_APPLE;
			break;
			case 323: returnMaterial = Material.SIGN;
			break;
			case 324: returnMaterial = Material.OAK_DOOR;
			break;
			case 325: returnMaterial = Material.BUCKET;
			break;
			case 326: returnMaterial = Material.WATER_BUCKET;
			break;
			case 327: returnMaterial = Material.LAVA_BUCKET;
			break;
			case 328: returnMaterial = Material.MINECART;
			break;
			case 329: returnMaterial = Material.SADDLE;
			break;
			case 330: returnMaterial = Material.IRON_DOOR;
			break;
			case 331: returnMaterial = Material.REDSTONE;
			break;
			case 332: returnMaterial = Material.SNOWBALL;
			break;
			case 333: returnMaterial = Material.OAK_BOAT;
			break;
			case 334: returnMaterial = Material.LEATHER;
			break;
			case 335: returnMaterial = Material.MILK_BUCKET;
			break;
			case 336: returnMaterial = Material.BRICK;
			break;
			case 337: returnMaterial = Material.CLAY_BALL;
			break;
			case 338: returnMaterial = Material.SUGAR_CANE;
			break;
			case 339: returnMaterial = Material.PAPER;
			break;
			case 340: returnMaterial = Material.BOOK;
			break;
			case 341: returnMaterial = Material.SLIME_BALL;
			break;
			case 342: returnMaterial = Material.CHEST_MINECART;
			break;
			case 343: returnMaterial = Material.STONE; //Powered minecart, not meant for use
			break;
			case 344: returnMaterial = Material.EGG;
			break;
			case 345: returnMaterial = Material.COMPASS;
			break;
			case 346: returnMaterial = Material.FISHING_ROD;
			break;
			case 347: returnMaterial = Material.CLOCK;
			break;
			case 348: returnMaterial = Material.GLOWSTONE_DUST;
			break;
			case 349: returnMaterial = Material.SALMON;
			break;
			case 350: returnMaterial = Material.COOKED_SALMON;
			break;
			case 351: returnMaterial = Material.INK_SAC;
			break;
			case 352: returnMaterial = Material.BONE;
			break;
			case 353: returnMaterial = Material.SUGAR;
			break;
			case 354: returnMaterial = Material.CAKE;
			break;
			case 355: returnMaterial = Material.RED_BED;
			break;
			case 356: returnMaterial = Material.REPEATER;
			break;
			case 357: returnMaterial = Material.COOKIE;
			break;
			case 358: returnMaterial = Material.MAP;
			break;
			case 359: returnMaterial = Material.SHEARS;
			break;
			case 360: returnMaterial = Material.MELON;
			break;
			case 361: returnMaterial = Material.PUMPKIN_SEEDS;
			break;
			case 362: returnMaterial = Material.MELON_SEEDS;
			break;
			case 363: returnMaterial = Material.BEEF;
			break;
			case 364: returnMaterial = Material.COOKED_BEEF;
			break;
			case 365: returnMaterial = Material.CHICKEN;
			break;
			case 366: returnMaterial = Material.COOKED_CHICKEN;
			break;
			case 367: returnMaterial = Material.ROTTEN_FLESH;
			break;
			case 368: returnMaterial = Material.ENDER_PEARL;
			break;
			case 369: returnMaterial = Material.BLAZE_ROD;
			break;
			case 370: returnMaterial = Material.GHAST_TEAR;
			break;
			case 371: returnMaterial = Material.GOLD_NUGGET;
			break;
			case 372: returnMaterial = Material.NETHER_WART;
			break;
			case 373: returnMaterial = Material.POTION;
			break;
			case 374: returnMaterial = Material.GLASS_BOTTLE;
			break;
			case 375: returnMaterial = Material.SPIDER_EYE;
			break;
			case 376: returnMaterial = Material.FERMENTED_SPIDER_EYE;
			break;
			case 377: returnMaterial = Material.BLAZE_POWDER;
			break;
			case 378: returnMaterial = Material.MAGMA_CREAM;
			break;
			case 379: returnMaterial = Material.BREWING_STAND;
			break;
			case 380: returnMaterial = Material.CAULDRON;
			break;
			case 381: returnMaterial = Material.ENDER_EYE;
			break;
			case 382: returnMaterial = Material.MELON_SLICE;
			break;
			case 383: returnMaterial = Material.STONE; //Monster egg
			break;
			case 384: returnMaterial = Material.EXPERIENCE_BOTTLE;
			break;
			case 385: returnMaterial = Material.STONE; //Fireball
			break;
			case 386: returnMaterial = Material.WRITABLE_BOOK;
			break;
			case 387: returnMaterial = Material.WRITTEN_BOOK;
			break;
			case 388: returnMaterial = Material.EMERALD;
			break;
			case 389: returnMaterial = Material.ITEM_FRAME;
			break;
			case 390: returnMaterial = Material.FLOWER_POT;
			break;
			case 391: returnMaterial = Material.CARROT;
			break;
			case 392: returnMaterial = Material.POTATO;
			break;
			case 393: returnMaterial = Material.BAKED_POTATO;
			break;
			case 394: returnMaterial = Material.POISONOUS_POTATO;
			break;
			case 395: returnMaterial = Material.MAP;
			break;
			case 396: returnMaterial = Material.GOLDEN_CARROT;
			break;
			case 397: returnMaterial = Material.SKELETON_SKULL;
			break;
			case 398: returnMaterial = Material.CARROT;
			break;
			case 399: returnMaterial = Material.NETHER_STAR;
			break;
			case 400: returnMaterial = Material.PUMPKIN_PIE;
			break;
			case 401: returnMaterial = Material.FIREWORK_ROCKET;
			break;
			case 402: returnMaterial = Material.FIREWORK_STAR;
			break;
			case 403: returnMaterial = Material.ENCHANTED_BOOK;
			break;
			case 404: returnMaterial = Material.COMPARATOR;
			break;
			case 405: returnMaterial = Material.NETHER_BRICKS;
			break;
			case 406: returnMaterial = Material.QUARTZ;
			break;
			case 407: returnMaterial = Material.TNT_MINECART;
			break;
			case 408: returnMaterial = Material.HOPPER_MINECART;
			break;
			case 409: returnMaterial = Material.PRISMARINE_SHARD;
			break;
			case 410: returnMaterial = Material.PRISMARINE_CRYSTALS;
			break;
			case 411: returnMaterial = Material.RABBIT;
			break;
			case 412: returnMaterial = Material.COOKED_RABBIT;
			break;
			case 413: returnMaterial = Material.RABBIT_STEW;
			break;
			case 414: returnMaterial = Material.RABBIT_FOOT;
			break;
			case 415: returnMaterial = Material.RABBIT_HIDE;
			break;
			case 416: returnMaterial = Material.ARMOR_STAND;
			break;
			case 417: returnMaterial = Material.IRON_HORSE_ARMOR;
			break;
			case 418: returnMaterial = Material.GOLDEN_HORSE_ARMOR;
			break;
			case 419: returnMaterial = Material.DIAMOND_HORSE_ARMOR;
			break;
			case 420: returnMaterial = Material.LEAD;
			break;
			case 421: returnMaterial = Material.NAME_TAG;
			break;
			case 422: returnMaterial = Material.STONE;
			break;
			case 423: returnMaterial = Material.MUTTON;
			break;
			case 424: returnMaterial = Material.COOKED_MUTTON;
			break;
			case 425: returnMaterial = Material.GRAY_BANNER;
			break;
			case 426: returnMaterial = Material.END_CRYSTAL;
			break;
			case 427: returnMaterial = Material.SPRUCE_DOOR;
			break;
			case 428: returnMaterial = Material.BIRCH_DOOR;
			break;
			case 429: returnMaterial = Material.JUNGLE_DOOR;
			break;
			case 430: returnMaterial = Material.ACACIA_DOOR;
			break;
			case 431: returnMaterial = Material.DARK_OAK_DOOR;
			break;
			case 432: returnMaterial = Material.CHORUS_FRUIT;
			break;
			case 433: returnMaterial = Material.CHORUS_FRUIT;
			break;
			case 434: returnMaterial = Material.BEETROOT;
			break;
			case 435: returnMaterial = Material.BEETROOT_SEEDS;
			break;
			case 436: returnMaterial = Material.BEETROOT_SOUP;
			break;
			case 437: returnMaterial = Material.DRAGON_BREATH;
			break;
			case 438: returnMaterial = Material.SPLASH_POTION;
			break;
			case 439: returnMaterial = Material.SPECTRAL_ARROW;
			break;
			case 440: returnMaterial = Material.TIPPED_ARROW;
			break;
			case 441: returnMaterial = Material.LINGERING_POTION;
			break;
			case 442: returnMaterial = Material.SHIELD;
			break;
			case 443: returnMaterial = Material.ELYTRA;
			break;
			case 444: returnMaterial = Material.SPRUCE_BOAT;
			break;
			case 445: returnMaterial = Material.BIRCH_BOAT;
			break;
			case 446: returnMaterial = Material.JUNGLE_BOAT;
			break;
			case 447: returnMaterial = Material.ACACIA_BOAT;
			break;
			case 448: returnMaterial = Material.DARK_OAK_BOAT;
			break;
			case 449: returnMaterial = Material.TOTEM_OF_UNDYING;
			break;
			case 450: returnMaterial = Material.SHULKER_SHELL;
			break;
			case 452: returnMaterial = Material.IRON_NUGGET;
			break;
			case 453: returnMaterial = Material.KNOWLEDGE_BOOK;
			break;
			case 2256: returnMaterial = Material.STONE; //Music disc
			break;
			case 2257: returnMaterial = Material.STONE; //Music disc
			break;
			case 2258: returnMaterial = Material.STONE; //Music disc
			break;
			case 2259: returnMaterial = Material.STONE; //Music disc
			break;
			case 2260: returnMaterial = Material.STONE; //Music disc
			break;
			case 2261: returnMaterial = Material.STONE; //Music disc
			break;
			case 2262: returnMaterial = Material.STONE; //Music disc
			break;
			case 2263: returnMaterial = Material.STONE; //Music disc
			break;
			case 2264: returnMaterial = Material.STONE; //Music disc
			break;
			case 2265: returnMaterial = Material.STONE; //Music disc
			break;
			case 2266: returnMaterial = Material.STONE; //Music disc
			break;
			case 2267: returnMaterial = Material.STONE; //Music disc
			break;
		}
		return returnMaterial;				
	}
}
